name: ci for prettier
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4

      - name: install depencies
        run: npm install

      - name: fix prettier issues
        run: npm run format

      - name: check prettier format
        run: npm run format:check

      - name: build project
        run : npm run build
